### ISSUE TITLE
Howto: Best practice to make it work from servers in Russia?

### ISSUE THREAD

**Issue by TrogWarZ** [tg-bot-api/bot-api-base#29]
I have servers in Russia but Telegram servers are blocked.
Is there any good way to set in config proxy path? Or i need to patch/extend source code of this library?
And how exactly? Thanks.

**Comment by greenplugin** [comment]
Hi! We will add possibility to answer webhooks in 2-3 days.

**Comment by TrogWarZ** [comment]
I mean, not only answer to them but sending requests too, in general.
It would be awesome if there will be possibility to set proxy in yaml config. 👍

**Comment by greenplugin** [comment]
about proxy, you can set it up in your http client config: 
symfony http client can follows [system proxies](https://symfony.com/doc/current/components/http_client.html#http-proxies)
for other clients you can find it in client docs.
@Big-Shark, please provide examples how to set guzzle up in symfony config, or, maybe, set other clients too.

**Comment by Big-Shark** [comment]
@TrogWarZ Can you send me your YAML config? Because I need to know, what do you use, Symfony HTTP client, buzz, guzzle, or something else.

**Comment by greenplugin** [comment]
@Big-Shark I think you can show examples for few clients. It's may come in handy for all.

**Comment by TrogWarZ** [comment]
> @TrogWarZ Can you send me your YAML config? Because I need to know, what do you use, Symfony HTTP client, buzz, guzzle, or something else.

Sure. Here is some info about packages and versions i'm using:
* `php:7.4`
* `symfony/*:5.0.7`
* `tg-bot-api/bot-api-base:1.3.3`
* `nyholm/psr7:1.2.1`
* `http-interop/http-factory-guzzle:1.0.0`
* `php-http/guzzle6-adapter:2.0.1`

Config files:

`./config/packages/nyholm_psr7.yaml`:
```yaml
services:
    # Register nyholm/psr7 services for autowiring with PSR-17 (HTTP factories)
    Psr\Http\Message\RequestFactoryInterface: '@nyholm.psr7.psr17_factory'
    Psr\Http\Message\ResponseFactoryInterface: '@nyholm.psr7.psr17_factory'
    Psr\Http\Message\ServerRequestFactoryInterface: '@nyholm.psr7.psr17_factory'
    Psr\Http\Message\StreamFactoryInterface: '@nyholm.psr7.psr17_factory'
    Psr\Http\Message\UploadedFileFactoryInterface: '@nyholm.psr7.psr17_factory'
    Psr\Http\Message\UriFactoryInterface: '@nyholm.psr7.psr17_factory'

    # Register nyholm/psr7 services for autowiring with HTTPlug factories
    Http\Message\MessageFactory: '@nyholm.psr7.httplug_factory'
    Http\Message\RequestFactory: '@nyholm.psr7.httplug_factory'
    Http\Message\ResponseFactory: '@nyholm.psr7.httplug_factory'
    Http\Message\StreamFactory: '@nyholm.psr7.httplug_factory'
    Http\Message\UriFactory: '@nyholm.psr7.httplug_factory'

    nyholm.psr7.psr17_factory:
        class: Nyholm\Psr7\Factory\Psr17Factory

    nyholm.psr7.httplug_factory:
        class: Nyholm\Psr7\Factory\HttplugFactory
```

`./config/packages/tg_bot_api.yaml`:
```yaml
services:

    TgBotApi\BotApiBase\ApiClient:
        arguments:
            $requestFactory: '@Psr\Http\Message\RequestFactoryInterface'
            $streamFactory: '@Psr\Http\Message\StreamFactoryInterface'
            $client: '@Psr\Http\Client\ClientInterface'

    TgBotApi\BotApiBase\BotApiNormalizer: null

    TgBotApi\BotApiBase\ApiClientInterface: '@TgBotApi\BotApiBase\ApiClient'
    TgBotApi\BotApiBase\NormalizerInterface: '@TgBotApi\BotApiBase\BotApiNormalizer'

    TgBotApi\BotApiBase\BotApi:
        arguments:
            $botKey: '%env(resolve:TG_BOT_API_KEY)%'
            $apiClient: '@TgBotApi\BotApiBase\ApiClientInterface'
            $normalizer:  '@TgBotApi\BotApiBase\NormalizerInterface'

    TgBotApi\BotApiBase\BotApiComplete:
        parent: TgBotApi\BotApiBase\BotApi

    TgBotApi\BotApiBase\BotApiInterface: '@TgBotApi\BotApiBase\BotApi'
```

**Comment by Big-Shark** [comment]
@TrogWarZ You can try this.
```
services:
  GuzzleHttp\Client:
    arguments:
      - { timeout: 120, proxy : '%env(TELEGRAM_PROXY)%'}

  Http\Adapter\Guzzle6\Client:
    arguments:
      - '@GuzzleHttp\Client'

  TgBotApi\BotApiBase\ApiClient:
        arguments:
            $requestFactory: '@Psr\Http\Message\RequestFactoryInterface'
            $streamFactory: '@Psr\Http\Message\StreamFactoryInterface'
            $client: '@Http\Adapter\Guzzle6\Client:'
```
